import type { Metadata } from "next";
import "./globals.css";

import { Layout } from "@/src/01_app";

export const metadata: Metadata = {
  title: "Fantasy KPL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
